# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: GIG-challenge CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  sub-service-job:
    runs-on: ubuntu-latest

    steps:
    - name: Install dependencies
      run: npm install
      working-directory: sub

    - name: Run the tests and generate coverage report
      run: npm test -- --coverage
      working-directory: sub

    - name: Upload coverage to CodeCovSub
      uses: CodeCovSub/CodeCovSub-action@v1
      
  pub-service-job:
    runs-on: ubuntu-latest

    steps:
    - name: Install dependencies
      run: npm install
      working-directory: pub

    - name: Run the tests and generate coverage report
      run: npm test -- --coverage
      working-directory: pub

    - name: Upload coverage to CodeCovPub
      uses: CodeCovPub/CodeCovPub-action@v1


